management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, hawtio, jolokia

endpoints:
  jolokia:
    sensitive: false

hawtio:
  authenticationEnabled: false

azure:
  jms:
    servicebus:
      enabled: false
      connection-string: ${HMCServiceBusConnectionString}
      wait-to-retry-time: ${SERVICE_BUS_IDLE_TIMEOUT:20}
      queue-name: ${HMCServiceBusQueueName}
  activemq:
    in-memory: true
  autoconfigure:
    exclude:
