server:
  port: 4558

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/"
  application:
    name: HMC HMI Outbound Adapter
  jackson:
    property-naming-strategy: SNAKE_CASE
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_OPTIONS:}
#    username: ${DB_USER_NAME}
#    password: ${DB_PASSWORD}
#    properties:
#      charSet: UTF-8
#    hikari:
#      minimumIdle: 2
#      maximumPoolSize: 10
#      idleTimeout: 10000
#      poolName: {to-be-defined}HikariCP
#      maxLifetime: 7200000
#      connectionTimeout: 30000
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            # silence the 'wall-of-text' - unnecessary exception throw about blob types
#            non_contextual_creation: true

azure:
  application-insights:
    instrumentation-key: ${hmc.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
  jms:
    servicebus:
      connection-string: ${HMCServiceBusConnectionString}
      wait-to-retry-time: ${SERVICE_BUS_IDLE_TIMEOUT:60}
      queue-name: ${HMCServiceBusQueueName}

fh:
  ad:
    host: ${FH_BASE_URL:base/url}
    get-token-url: ${FH_GET_TOKEN_URL:get/token/url}
    client-id: ${CLIENT_ID:client-id}
    client-secret: ${CLIENT_SECRET:client-secret}
    scope: ${SCOPE:scope}
    grant-type: ${GRANT_TYPE:grant-type}
  hmi:
    host: ${HMI_BASE_URL:base/url}
    source-system: ${HMI_SOURCE_SYSTEM:source-system}
    destination-system: ${HMI_DESTINATION_SYSTEM:destination-system}

feign:
  okhttp:
    enabled: true
