management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, hawtio, jolokia

endpoints:
  jolokia:
    sensitive: false

hawtio:
  authenticationEnabled: false

azure:
  jms:
    servicebus:
      enabled: false
      connection-string: ${SB_CONN_STRING:Endpoint=sb://hmc-servicebus-demo.servicebus.windows.net/;SharedAccessKeyName=lsiten;SharedAccessKey=HwilWAXv3FXJljxOQcSS1TFwUxpx+cphH7pGleyV30g=;EntityPath=rebecca-test}
      wait-to-retry-time: ${SERVICE_BUS_IDLE_TIMEOUT:20}
      queue-name: ${SERVICE_BUS_QUEUE_NAME:rebecca-test}
  activemq:
    in-memory: true
  autoconfigure:
    exclude:
