fh:
  ad:
    host: http://localhost:${wiremock.server.port:5000}
    get-token-url: /FH_GET_TOKEN_URL
    client-id: CLIENT_ID
    client-secret: CLIENT_SECRET
    scope: SCOPE
    grant-type: GRANT_TYPE

spring:
  jms:
    servicebus:
      connection-string: ${SB_CONN_STRING}
      wait-to-retry-time: ${SERVICE_BUS_IDLE_TIMEOUT:1800000}
      queue-name: ${SERVICE_BUS_QUEUE_NAME:hmc-to-hmi-queue}
