java:
  applicationPort: 4558
  image: 'hmctspublic.azurecr.io/hmc/hmi-outbound-adapter:latest'
  ingressHost: hmc-hmi-outbound-adapter-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: hmc
  keyVaults:
    hmc:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: CLIENT_ID
          alias: fh.ad.client-id
        - name: ClientSecret
          alias: CLIENT_SECRET
        - name: Scope
          alias: SCOPE
        - name: hmc-servicebus-connection-string
          alias: HMC_SERVICE_BUS_CONNECTION_STRING
  environment:
    HMC_SERVICE_BUS_QUEUE: hmc-to-hmi-{{ .Values.global.environment }}

servicebus:
  enabled: false
