java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    SERVICE_BUS_QUEUE_NAME: hmc-to-hmi-{{ .Release.Name }}
  secrets:
    SB_CONN_STRING:
      secretRef: servicebus-secret-queue-{{ .Release.Name }}-servicebus-hmc-to-hmi
      key: connectionString
  keyVaults:
    hmc:
      resourceGroup: hmc-shared
      secrets:
        - name: AppInsightsInstrumentationKey

servicebus:
  enabled: true
  teamName: CCD
  resourceGroup: hmc-aks
  serviceplan: standard
  setup:
    queues:
      -name: hmc-to-hmi
