java:
  applicationPort: 4558
  image: 'hmctspublic.azurecr.io/hmc/hmi-outbound-adapter:latest'
  ingressHost: hmc-hmi-outbound-adapter-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: hmc
  keyVaults:
    hmc:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: ClientId
          alias: fh.ad.client-id
        - name: ClientSecret
          alias: fh.ad.client-secret
        - name: Scope
          alias: fh.ad.scope
        - name: HMCServiceBusConnectionString
          alias: azure.jms.servicebus.connection-string
  environment:
    HMC_SERVICE_BUS_QUEUE: hmc-to-hmi-{{ .Values.global.environment }}

servicebus:
  enabled: false
