java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    hmc:
      resourceGroup: hmc-shared
      secrets:
        - name: AppInsightsInstrumentationKey
        SERVICE_BUS_CONNECTION_STRING:
          secretRef: servicebus-secret-{{ .Release.Name }}-servicebus
          key: connectionString

servicebus:
  enabled: true
  teamName: CCD
  resourceGroup: hmc-aks
  serviceplan: standard
  setup:
    queue:
      -name: {{ .Release.Name }}-queue
