java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    hmc:
      resourceGroup: hmc-shared
      secrets:
        - name: AppInsightsInstrumentationKey
        SB_CONN_STRING:
          secretRef: servicebus-secret-queue-{{ .Release.Name }}-servicebus-hmc-to-hmi
          key: connectionString

servicebus:
  enabled: true
  teamName: CCD
  resourceGroup: hmc-aks
  serviceplan: standard
  setup:
    queues:
      -name: hmc-to-hmi-{{ .Release.Name }}
